name: 'build'

on:
  push:
    branches:
      - master

jobs:
  publish-tauri:
    if: contains(github.event.head_commit.message, 'chore(release)')
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf cmake libcurl4-openssl-dev libuv1-dev

      - name: install frontend dependencies
        run: yarn install
      
      - name: Set up GCC (Linux)
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
          sudo apt-get update
          sudo apt-get install software-properties-common -y
          sudo apt-get install gcc-13 g++-13 -y
          sudo rm -f /usr/bin/gcc && sudo rm -f /usr/bin/g++
          sudo ln -s /usr/bin/gcc-13 /usr/bin/gcc && sudo ln -s /usr/bin/g++-13 /usr/bin/g++

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: app-v__VERSION__
          releaseName: 'App v__VERSION__'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          prerelease: false